import { useEffect, useMemo, useState } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/AlertDialog";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { TimeText } from "@/components/ui/TimeText";
import type { SendRequestFilters } from "@/features/admin/AdminPages";
import { apiFetch } from "@/lib/api";
import { MobilePage } from "../MobilePage";
import { MobileCardAction, MobileEntityCard } from "./MobileEntityCard";
import { getMobileSendRequestConversationName, mobileSendRequestBadgeStatus, MobileSendRequestDetailPage, type MobileSendRequestRecord } from "./MobileSendRequestDetailPage";

const DEFAULT_FILTERS: SendRequestFilters = { status: "", page: 1, pageSize: 20 };
const OPTIONS: Array<{ label: string; value: SendRequestFilters["status"] }> = [{ label: "全部", value: "" }, { label: "成功", value: "success" }, { label: "失败", value: "failed" }, { label: "进行中", value: "in_progress" }, { label: "结果未知", value: "unknown" }];
export function MobileSendRequestsPage({ initialFilters = DEFAULT_FILTERS, onFiltersChange, onBack }: { initialFilters?: SendRequestFilters; onFiltersChange?: (filters: SendRequestFilters) => void; onBack?: () => void }) {
  const [filters, setFilters] = useState(initialFilters); const [records, setRecords] = useState<MobileSendRequestRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<MobileSendRequestRecord | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState<string | null>(null); const [confirming, setConfirming] = useState<{ kind: "revoke" | "cancel"; row: MobileSendRequestRecord } | null>(null); const [acting, setActing] = useState(false); const [actionError, setActionError] = useState<string | null>(null);
  const path = useMemo(() => buildPath(filters), [filters]); useEffect(() => setFilters(initialFilters), [initialFilters]);
  useEffect(() => { let cancelled = false; setLoading(true); void apiFetch<MobileSendRequestRecord[]>(path).then((data) => { if (!cancelled) { setRecords(data); setError(null); } }).catch((failure) => { if (!cancelled) setError(failure instanceof Error ? failure.message : "数据加载失败"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [path]);
  const update = (next: SendRequestFilters) => { setFilters(next); onFiltersChange?.(next); }; const reload = async () => { setLoading(true); try { setRecords(await apiFetch<MobileSendRequestRecord[]>(path)); setError(null); } catch (failure) { setError(failure instanceof Error ? failure.message : "数据加载失败"); } finally { setLoading(false); } };
  const openDetail = async (row: MobileSendRequestRecord) => { setSelected(row); setDetailLoading(true); setDetailError(null); try { setSelected(await apiFetch<MobileSendRequestRecord>(`/api/send-requests/${row.id}`)); } catch (failure) { setDetailError(failure instanceof Error ? failure.message : "发送详情加载失败"); } finally { setDetailLoading(false); } };
  const act = async () => { if (!confirming || acting) return; setActing(true); setActionError(null); const messageId = confirming.row.message?.messageId; try { if (confirming.kind === "revoke" && messageId) await apiFetch(`/api/messages/${encodeURIComponent(messageId)}/revoke`, { method: "POST" }); else await apiFetch(`/api/send/${confirming.row.id}/cancel`, { method: "POST" }); await reload(); setConfirming(null); } catch (failure) { setActionError(failure instanceof Error ? failure.message : "操作失败"); } finally { setActing(false); } };
  if (selected) return <MobileSendRequestDetailPage request={selected} loading={detailLoading} error={detailError} onBack={() => setSelected(null)} />;
  const visible = records.filter((row) => { const q = search.trim().toLowerCase(); return !q || [row.id, row.type, row.status, row.deliveryMode, row.message?.messageId, getMobileSendRequestConversationName(row)].some((v) => String(v ?? "").toLowerCase().includes(q)); });
  return <MobilePage title="发送记录" subtitle="追踪后台和应用发起的发送请求" onBack={onBack}><div className="grid gap-3 p-4">
    <div role="region" aria-label="发送记录状态" className="flex gap-2 overflow-x-auto pb-1">{OPTIONS.map((o) => <button key={o.value} type="button" aria-pressed={filters.status === o.value} onClick={() => update({ ...filters, status: o.value, page: 1 })} className="min-h-10 shrink-0 rounded-full border px-4 text-sm aria-pressed:border-primary aria-pressed:bg-primary/10">{o.label}</button>)}</div>
    <div className="flex gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="搜索发送记录" className="min-h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm"/><button type="button" aria-label="刷新" onClick={() => void reload()} className="min-h-11 rounded-xl border px-4">刷新</button></div>
    {loading ? <p>正在加载</p> : null}{error ? <p className="text-destructive">{error}</p> : null}{actionError ? <p className="text-destructive">{actionError}</p> : null}{!loading && visible.length === 0 ? <p>{search ? "没有匹配的发送记录" : "暂无发送记录"}</p> : null}
    <div role="list" aria-label="发送记录列表" className="grid gap-3">{visible.map((row) => { const canRevoke = row.status === "sent" && Boolean(row.message?.messageId); const canCancel = ["pending", "failed", "unknown"].includes(row.status); return <div role="listitem" key={row.id}><MobileEntityCard title={getMobileSendRequestConversationName(row)} subtitle={<code>{row.id}</code>} badge={<StatusBadge status={mobileSendRequestBadgeStatus(row.status)}/>} details={<><span>{row.type} · {row.deliveryMode ?? "immediate"}</span><span>结果 {row.message?.messageId || (row.status === "pending" ? "等待中" : row.status === "unknown" ? "结果未知" : "—")}</span><span>创建时间 <TimeText value={row.updatedAt}/></span></>} actions={<><MobileCardAction aria-label={`查看发送详情 ${row.id}`} onClick={() => void openDetail(row)}>详情</MobileCardAction><MobileCardAction aria-label={`撤回 ${row.id}`} disabled={!canRevoke} onClick={() => setConfirming({ kind: "revoke", row })}>撤回</MobileCardAction><MobileCardAction aria-label={`取消发送重试 ${row.id}`} disabled={!canCancel} onClick={() => setConfirming({ kind: "cancel", row })}>取消重试</MobileCardAction></>}/></div>; })}</div>
    <div className="grid grid-cols-2 gap-2"><button type="button" aria-label="上一页" disabled={filters.page <= 1 || loading} onClick={() => update({ ...filters, page: filters.page - 1 })} className="min-h-11 rounded-xl border disabled:opacity-40">上一页</button><button type="button" aria-label="下一页" disabled={records.length < filters.pageSize || loading} onClick={() => update({ ...filters, page: filters.page + 1 })} className="min-h-11 rounded-xl border disabled:opacity-40">下一页</button></div>
  </div><AlertDialog open={Boolean(confirming)} onOpenChange={(open) => { if (!open && !acting) setConfirming(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirming?.kind === "revoke" ? "撤回发送消息" : "取消发送重试"}</AlertDialogTitle><AlertDialogDescription>{confirming?.kind === "revoke" ? "撤回后将调用 GeWe 撤回接口，微信侧消息会尝试显示为已撤回。" : "取消后会终止关联发送任务，避免同一文件或图片继续重复发送。"}</AlertDialogDescription></AlertDialogHeader><p className="break-all">{confirming?.kind === "revoke" ? confirming.row.message?.messageId : confirming?.row.id}</p><AlertDialogFooter><AlertDialogCancel disabled={acting}>取消</AlertDialogCancel><AlertDialogAction disabled={acting} onClick={(e) => { e.preventDefault(); void act(); }}>{confirming?.kind === "revoke" ? "确认撤回" : "确认取消"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></MobilePage>;
}
function buildPath(filters: SendRequestFilters) { const p = new URLSearchParams({ take: String(filters.pageSize), skip: String((filters.page - 1) * filters.pageSize) }); if (filters.status) p.set("status", filters.status); return `/api/send-requests?${p.toString()}`; }
